baseURL: "https://pierrebard.github.io/pierre-bardier/"
title: Pierre Bardier
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Teaching
          url: teaching/
          weight: 2
        - name: Events
          url: events/
          weight: 3
        - name: Curriculum
          url: curriculum/
          weight: 4
        - name: Contact
          url: contact/
          weight: 5

params:
    description: "I am a Ph.D student in theoretical economics at Paris School of Economics and École Normale Supérieure de Paris"
    author: Pierre Bardier
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pierre Bardier
          subtitle: "
          I am a Ph.D student in **theoretical economics** at **[Paris School of Economics](https://www.parisschoolofeconomics.eu/en/)** and **[École Normale Supérieure de Paris.](https://www.ens.psl.eu/)** My research spans **economic design and welfare economics**, with a specific focus on fair division, social choice, voting, and individual decision making. I am extremely happy to work under the supervision of **[Marc Fleurbaey.](https://sites.google.com/site/marcfleurbaey/Home)**<br><br>
          I had the pleasure to visit twice the department of economics of the **[University of Rochester](https://www.sas.rochester.edu/eco/)** at the invitation of Professor **[William Thomson.](https://sites.google.com/view/williamthomson)** <br><br>
          Before my Ph.D, I was studying at *[École Normale Supérieure de Paris](https://www.ens.psl.eu/)* for 5 years, during which I completed in particular a **MSc in economics** at *[Paris School of Economics](https://www.parisschoolofeconomics.eu/en/)* and a **MSc in mathematics** at *[Paris-I-Panthéon-Sorbonne.](https://www.pantheonsorbonne.fr/)*
          "
          imageUrl: "Photo site internet 5.JPG"
          imageWidth: 220
          imageHeight: 240
          #imageTitle: Pierre Bardier
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: Events
              url: events/
            - name: Curriculum
              url: curriculum/
            - name: Contact
              url: contact/
    socialIcons:
            - name: CV
              url: CV_Sep_2026.pdf
       # - name: Google Scholar
        #  url: https://scholar.google.com/
            - name: Arxiv
              url: https://arxiv.org/search/?query=Pierre+Bardier&searchtype=all&abstracts=show&order=-announced_date_first&size=50
            - name: LinkedIn
              url: https://www.linkedin.com/in/pierre-bardier-a817b3228/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Pierre Bardier"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
